name: honeyenv
channels:
  - defaults
dependencies:
  - ca-certificates=2017.08.26=h1d4fec5_0
  - certifi=2018.1.18=py36_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - ncurses=6.0=h9df7e31_2
  - openssl=1.0.2n=hb7f436b_0
  - pip=9.0.1=py36h6c6f9ce_4
  - python=3.6.4=hc3d631a_1
  - readline=7.0=ha6073c6_4
  - setuptools=38.4.0=py36_0
  - sqlite=3.22.0=h1bed415_0
  - tk=8.6.7=hc745277_3
  - wheel=0.30.0=py36hfd4bba0_1
  - xz=5.2.3=h55aa19d_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - chardet==3.0.4
    - docker-py==1.10.6
    - docker-pycreds==0.2.3
    - idna==2.6
    - python-nmap==0.6.1
    - requests==2.18.4
    - six==1.11.0
    - urllib3==1.22
    - websocket-client==0.47.0
